### ISSUE TITLE
Provision Encrypted Database (Postgres) AWS

### ISSUE THREAD

**Issue by knocknarea** [boxfuse/boxfuse-issues#206] opened 2018-03-21 18:16 UTC
Is it possible for boxfuse to enable encryption for a database that it provisions on AWS?

It's only possible to do this on database creation.

**Comment by axelfontaine** [comment] 2018-03-21 18:57
This is not yet supported, but it has a firm place on our roadmap.

**Comment by knocknarea** [comment] 2018-03-26 21:42
@axelfontaine 

Let's say you have configured an app (spring + database) and have it happily deployed on a staging environment where you don't mind that it's a provisioned database. However, for production you want to use an encrypted database (and so need to provision and configure it yourself)

Is it possible to deploy it to production on a non-provisioned basis, i.e. db.type=none or do I have to tear it all down and start again by recreating the app with the db.type=none

BTW: this is a bit urgent for us...

**Comment by knocknarea** [comment] 2018-03-26 22:29
@axelfontaine 
Thanks for the swift reply and advise. Luckily with boxfuse I can just tear it down and bring it back up easily enough.

When you say refer to the manually created second database, how do I do that?

**Comment by axelfontaine** [comment] 2018-03-26 22:45
You can for example activate a different Spring profile with the alternative config.

**Comment by knocknarea** [comment] 2018-03-26 22:46
@axelfontaine 
Very good. Thanks for your help on this. All sorted now.

**Comment by axelfontaine** [comment] 2021-01-30 22:21
Duplicate of #143

**Closed by axelfontaine** 2021-01-30 22:21 UTC
Labels: d: postgresql, p: aws, t: feature
